name: Cypress Tests

on:
  push:
    branches:
      - main
      - master
      - develop
      - test/cypress-desafio
  pull_request:

jobs:
  cypress-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes de API no Chrome headless
        run: npx cypress run --spec "cypress/e2e/api/usuarios.cy.js"

  cypress-frontend:
    runs-on: ubuntu-latest
    needs: cypress-api
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes de Frontend no Chrome headless
        run: npx cypress run --spec "cypress/e2e/frontend/cadastro.cy.js"